spring:
  application:
    name: zadanie
  datasource:
    url: jdbc:h2:mem:zadanie;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    username: sa
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  liquibase:
    change-log: classpath:db/changelog/changelog-master.yaml
  cache:
    type: simple
