spring:
  application:
    name: zadanie
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://db:5432/zadanie}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  liquibase:
    change-log: classpath:db/changelog/changelog-master.yaml
  cache:
    type: simple
server:
  port: 8080
